kind: Deployment
apiVersion: apps/v1
metadata:
  name: jmeter-container
  labels:
    app.kubernetes.io/part-of: jmeter-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-container
  template:
    metadata:
      labels:
        app: jmeter-container
        deployment: jmeter-container
    spec:
      initContainers:
        - name: load-booking
          image: 'registry.access.redhat.com/ubi8/ubi:latest'
          command:
            - sh
            - '-c'
            - 'curl http://"$(HOST)":"$(PORT)"/booking/loader/load'
          envFrom:
            - configMapRef:
                name: cm-acmeair
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: load-flight
          image: 'registry.access.redhat.com/ubi8/ubi:latest'
          command:
            - sh
            - '-c'
            - 'curl http://"$(HOST)":"$(PORT)"/flight/loader/load'
          envFrom:
            - configMapRef:
                name: cm-acmeair
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: load-customer
          image: 'registry.access.redhat.com/ubi8/ubi:latest'
          command:
            - sh
            - '-c'
            - >-
              curl
              http://"$(HOST)":"$(PORT)"/customer/loader/load?numCustomers=10000
          envFrom:
            - configMapRef:
                name: cm-acmeair
      volumes:
        - name: jmeter-test
          configMap:
            name: jmeter-test
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: jmeter-container
          ports:
            - containerPort: 9080
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: jmeter-test
              mountPath: /etc/jmeter-driver
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: cm-acmeair
          image: >-
            quay.io/mmondics/jmeter-container:manifest-v2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
